### ISSUE TITLE
Advanced Rocketry server crash when loading chunks on custom planets

### ISSUE THREAD

**Issue by Firecube247** [EnigmaticaModpacks/Enigmatica2Expert#1973] opened 2021-11-26 21:47 UTC
### Modpack Version

1.83

### Describe your issue.

When I enter a planet like Stella or Terra Nova and start loading chunks, the server crashes. This does not happen on planets in the solar system like Luna or Neptune. Here is the crash report to this issue: https://pastebin.com/zhHPSFEH

After making a bug report under the Advanced Rocketry GitHub page, [I was told to update to a newer version](https://github.com/Advanced-Rocketry/AdvancedRocketry/issues/2269), however this makes the modpack crash during startup. Here is the other crash report to the new issue: https://pastebin.com/NF27MueC

### Crash Report

Issue 1: https://pastebin.com/zhHPSFEH // Issue 2: https://pastebin.com/NF27MueC

### Latest Log

Too large for pastebin. Will provide if asked for.

### Have you modified the modpack?

Yes

### User Modifications

I tried updating Advanced Rocketry from version 2.0.0.-250 to 2.0.0.-256.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment] 2021-11-26 22:26
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-11-26 22:27
Did you also update LibVulpes when you tried updating AR? :)

**Comment by Firecube247** [comment] 2021-11-27 00:25
Ah, my bad, I forgot to update that as well. The modpack does start now, however the first issue is still leading to a crash. I'll reopen the thread on the Advanced Rocketry page.

**Comment by Silfryi** [comment] 2021-11-27 00:31
So, I am going to put this here - I briefly caused this bug due to a thing between BoP fluids and AR, I think - and I cannot remember if it corrupted worlds due to how I had it set up. If it did, the world is borked and you're going to need to delete the chunk/world to fix it.

**Comment by Firecube247** [comment] 2021-11-27 01:05
I'm not really sure if you implied that I should delete my world in hopes for a fix but I deleted the dimension folders to see if the world generation of the latest version would somehow change anything, however it's still crashing.

**Comment by Silfryi** [comment] 2021-11-27 01:34
I meant `World` in the code sense of a `World` object is a dimension, sorry that wasn't clear. Still crashing, hmmmm. I might try this at some point but we've mostly moved on from 1.12 now due to 1.16 taking a huge amount of time. I'll see if I can squeeze this in through the GH web interface and get it to compile.

**Comment by Terra-B-Welch** [comment] 2022-02-02 22:07
I wonder if the issue I ran into is related to this, I attempted to land on Stella on the enigmatica 2 expert server I'm playing on and the entire server died, the server is set up to auto-restart, but it seems I can't log into the server now without triggering another crash.

I cut out the error here, as the actual log is 1.7 million characters long so I dont think it'd even fit on pastebin.
https://pastebin.com/G3ST3HAJ

**Comment by jlfree12** [comment] 2022-02-02 23:01
I don’t know if its the same issue, but I crashed instantly when I loaded stella as well. Maybe the issue is with that planet or something to do with the type of BOP biome that is used for it.

**Comment by Terra-B-Welch** [comment] 2022-02-02 23:26
I do know that the server owner had to restore a backup since I couldn't log into the server without crashing it due to this crash.

**Comment by NillerMedDild** [comment] 2022-02-03 05:25
Seems there's some block on Stella that Advanced Rocketry's atmosphere checker reeeally hates.

**Comment by NillerMedDild** [comment] 2022-02-03 05:33
Would someone mind checking if this happens on Novus or Kepler 0118?

**Comment by NillerMedDild** [comment] 2022-02-03 14:52
That'd be nice 😀

**Comment by Terra-B-Welch** [comment] 2022-02-03 15:53
Ok test on Stella and Terra Nova on the latest AR and Libvulpes build done(builds 257 and 88)

The crash still occurs. (Exact same logs as the ones provided, looks like AR planets really don't like water generation.)

Going to test Novus and Kepler 0118 in both current E2E AR and Libvulpes builds and on latest builds.

Kinda a shame really, I was hoping to land on one of these planets if it had a breathable atmosphere and actually build another house on it, then connect via mekanism teleporter.

**Comment by Terra-B-Welch** [comment] 2022-02-03 16:14
Just flew around Novus and Kepler 0118, didn't encounter any crashes or other issues.

**Comment by NillerMedDild** [comment] 2022-02-04 15:09
Would you mind supplying the logs even though they're identical? 😀

**Comment by Terra-B-Welch** [comment] 2022-02-04 16:39
Heres pastebins for both crash reports, is that good enough?
https://pastebin.com/HcAq1APj
https://pastebin.com/Sp6HD81W

**Comment by Arithmion** [comment] 2022-02-10 22:04
Here's the log from Stella, I can walk around for like 30 seconds before I get hard crashed.
[latest.log](https://github.com/EnigmaticaModpacks/Enigmatica2Expert/files/8044620/latest.log)
.

**Comment by pclewisnz** [comment] 2022-02-27 04:07
I only just went to another star system in my single player E2E which contains AR 2.0.0.-250 and Vulpes 0.4.2.-83.
I had first issue with Terra Nova.  I presumed later it was due to the massive workrate needed for game to generate crags biome.  
After I closed my not responding game and reloaded I was spawned in space at altitude and fell to the ground which was actually there.  Soon after my rocket landed.  I went to Novus and no issue.  I went to Stella and this was same as Terra Nova only time I made mistake of using rocket pack to gain height to re-aquire the rocket and entering it with right click.  Then I pressed space to descend so it got non responsive again.  Third time I reloaded and did nothing but it also went non responsive after I dropped a hundred or so in the altitude (falling I presume as no rocket around me).  It looked like I rubber banded back to higher altitude and at that point it went unresponsive.  Fourth try I changed game settings to make render distance down form 8 chunks to 2 chunks.  This time I fell safely to the surface.
I don't know if it was changing to 2 chunks to give world a chance to generate or if it was my cumulative retries that resulted in enough world for me to fall to.  Either way, this note is possibly going to help someone out if they don't have another means to  teleport away form their doomed landing...

**Comment by Terra-B-Welch** [comment] 2022-02-27 12:14
So I guess the only option is to somehow disable BoP hot spring water? If that's whats causing the crash, if I'm understanding correctly.

(Also I failed to check if Stella had a breathable atmosphere or if it was "VeryHot" like Terra Nova and Proxima B are, not related to the issue, but I was looking around to see if any of the custom planets had a breathable atmosphere as I wanted to build a house on one >.<)

**Comment by NillerMedDild** [comment] 2022-02-27 12:17
I think the safest is to change to other biomes tbh :/ I removed the biome constraints in-dev so they'll generate with random biomes based on temperature and atmosphere.

**Comment by pclewisnz** [comment] 2022-02-28 19:11
My guess is that these biomes may be designed well enough for being part of
a world but not suitable as an entire planet.  The generation must be too
taxing on all but the most powerful systems.  Mine is decent but not super.
[image: image.png]
[image: image.png]

**Comment by Terra-B-Welch** [comment] 2022-03-01 00:18
Sorry for being a little off topic, but is stella habitable or is it VeryHot like Terra Nova and Proxima B?
I thought it'd be the one breathable atmosphere planet since with the sacred springs biome it has now(despite crashes) it has water and trees.

**Comment by NillerMedDild** [comment] 2022-03-01 05:10
I intended Terra Nova and Stella to be habitable, the temperature based on distance to sun thing was added recently. Maybe changing that would actually fix this issue 🤔

**Comment by Terra-B-Welch** [comment] 2022-03-01 12:23
So the crash was in fact distance related? Was it possibly BoP hot spring water getting evaporated from the planets being too close to their star and that by making them more distant from their star that they arren't "veryhot" anymore?

**Comment by Silfryi** [comment] 2022-03-01 12:26
As stated upon the linked issue in AR, I think so yes. What I  _think_ happens is that I get stuck in an endless loop due to how BoP handles the removal of blockstates from the world when they are hot spring water - possibly due to how it deals with turning things into water/not letting it get moved. (this is why the error is a SOF)

**Comment by Terra-B-Welch** [comment] 2022-03-01 13:12
So it's possible that if the hot spring water didn't evaporate that no crash would happen then?
I still have the E2E test instance, so I will try the 200 distance change myself.

**Comment by Zimpari** [comment] 2022-03-21 15:31
So does this mean the world is bricked now? 
How to get out of the loop of "landing" from the planet Stella?

**Comment by Silfryi** [comment] 2022-03-21 15:56
World is bricked unless you move planets with hot spring water biomes into the habitable zone

**Comment by Terra-B-Welch** [comment] 2022-03-21 16:00
> World is bricked unless you move planets with hot spring water biomes into the habitable zone

I must ask, do planet stats even update on existing worlds when the planets are modified or does it require a new world?

As I remember setting stella and terra nova's distance to 200 like the fix said, but the atmosphere analyzer in the test world still said "VeryHot"

**Comment by Silfryi** [comment] 2022-03-21 17:03
Editing the planets of a current world is a little funky, but if you edit the XML _and_ the `temp.dat` (the second with a NBT editor) it should function just fine, as long as the world is not open at the time, as both are saved on world close.

**Comment by Terra-B-Welch** [comment] 2022-04-08 12:32
The distance and temp thing works for those who want to edit their existing world to apply the fix, I know I'm slow on the draw but I did eventally end up testing that, and was able to fly around the planets without any crashing, and noticed many pools of hot spring water so I can confirm that it's fixed.

**Comment by MirrorImageQS** [comment] 2022-10-10 23:12
I was able to recreate this issue on Mercury as well. It's the same StackOverflowError centered around `zmaster587.advancedRocketry.atmosphere.AtmosphereHandler.onBlockChange`. Crash log indicates it's an issue with water again.

```
-- Block being updated --
Details:
	Source block type: ID #8 (tile.water // net.minecraft.block.BlockDynamicLiquid // minecraft:flowing_water)
	Block: minecraft:water[level=0]
	Block location: World: (-1563,57,-1522), Chunk: (at 5,3,14 in -98,-96; contains blocks -1568,0,-1536 to -1553,255,-1521), Region: (-4,-3; contains chunks -128,-96 to -97,-65, blocks -2048,0,-1536 to -1537,255,-1025)
```

This after I updated both Advanced Rocketry and LibVulpes to their most recent versions (2.0.0-13 and 0.4.2-25-universal, both released 5/22/22).

Mercury config is as default:
```xml
		<planet name="Mercury" DIMID="101" customIcon="lava">
			<skyColor>0,0,0</skyColor>
			<atmosphereDensity>120</atmosphereDensity>
			<gravitationalMultiplier>38</gravitationalMultiplier>
			<orbitalDistance>40</orbitalDistance>
			<rotationalPeriod>1400000</rotationalPeriod>
		</planet>
```

Looking at the built planetDef.xml from my world save, I noticed that it decided to add the biome `advancedrocketry:marsh` alongside the mutated savanna biomes. Editing the planetDefs.xml and temp.dat to remove the marsh biome un-breaks Mercury in a test world for me.

```xml
        <planet DIMID="101" customIcon="lava" name="Mercury">
            <isKnown>false</isKnown>
            <fogColor>1.0,1.0,1.0</fogColor>
            <skyColor>0.0,0.0,0.0</skyColor>
            <gravitationalMultiplier>38</gravitationalMultiplier>
            <orbitalDistance>40</orbitalDistance>
            <orbitalTheta>0</orbitalTheta>
            <orbitalPhi>0</orbitalPhi>
            <retrograde>false</retrograde>
            <avgTemperature>476</avgTemperature>
            <rotationalPeriod>1400000</rotationalPeriod>
            <atmosphereDensity>120</atmosphereDensity>
            <generateCraters>false</generateCraters>
            <generateCaves>false</generateCaves>
            <generateVolcanos>false</generateVolcanos>
            <generateStructures>false</generateStructures>
            <generateGeodes>false</generateGeodes>
            <biomeIds>minecraft:mutated_savanna_rock;30,advancedrocketry:marsh;30,minecraft:desert_hills;30,minecraft:mutated_mesa_rock;30,minecraft:mutated_mesa_clear_rock;30</biomeIds>
        </planet>
```

Having gotten the issue on Stella and Terra Nova as well, I see for those ones that it added advancedrocketry:oceanspires and minecraft:mutated_jungle. I suspect those are the two biomes that were in conflict there, but I solved those ones already by fixing the orbitalDistance to 200 as suggested above. Scanning through the other biomeIds it applied to other planets, none of them jump out with anything suspect to me.

@Silfryi So this might turn back into an Advanced Rocketry issue of why does it think high-temperature planets like these should be getting these very aquatic biomes - if not in principle, then at least when the existence of water causes this crash.

**Closed** 2022-10-15 17:48 UTC
Labels: Mod Issue, Status: Fixed In Next Release
