### ISSUE TITLE
The crusher is very, very slow.

### ISSUE THREAD

**Issue by MrNoide** [EnigmaticaModpacks/Enigmatica2Expert#2099] opened 2023-02-11 13:06 UTC
### Modpack Version

1.86

### Describe your issue.

So, I have been playing this modpack for a while and I made a crusher from Immersive Engineering to start ore doubling, however, it was very slow, taking minutes to crush one iron ore. I have enough power, has my batteries are full.

### Latest Log

https://gist.github.com/MrNoide/087398aa1e27f7fcba8be1c80b46e416

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment] 2023-02-11 21:00
Duplicate of #1841 - See this link for a temp fix: https://github.com/EnigmaticaModpacks/Enigmatica2Expert/issues/1841#issuecomment-735009413

**Closed by NielsPilgaard** 2023-02-11 21:00 UTC
Labels: Bug

**Comment by MrNoide** [comment] 2023-02-12 00:59
Where can I apply that change of changing that numbers to 1.0? Sorry for
bothering you.

Niels Pilgaard Grøndahl ***@***.***> escreveu em sáb.,
11/02/2023 às 21:00 :

**Comment by NielsPilgaard** [comment] 2023-02-12 07:18
`config/Netherending Ores.cfg`: https://github.com/EnigmaticaModpacks/Enigmatica2Expert/commit/2751bea2dd6bf8500fb568c06a1d571644fe59ad

**Comment by MrNoide** [comment] 2023-02-12 11:50
This already is set to 1.0

Em dom., 12 de fev. de 2023 às 07:18, Niels Pilgaard Grøndahl <
***@***.***> escreveu:

**Comment by NielsPilgaard** [comment] 2023-02-12 12:42
Both of those multilpiers? You also need to restart your game for the change to apply.

**Comment by MrNoide** [comment] 2023-02-12 12:44
When opened the file that was already set to 1.0, I haven’t changed anything

Niels Pilgaard Grøndahl ***@***.***> escreveu em dom.,
12/02/2023 às 12:42 :
