### ISSUE TITLE
Advanced Rocketry Crash upon loading hot planets (probably)

### ISSUE THREAD

**Issue by Us3rNqmed** [EnigmaticaModpacks/Enigmatica2Expert#2047] opened 2022-10-15 12:38 UTC
### Modpack Version

1.83

### Describe your issue.

Crashing upon loading chunks in a hot planet like Stella.

### Crash Report

https://gist.github.com/Us3rNqmed/9c6e90fa73607c9dfa2180cd1d38fe95

### Have you modified the modpack?

Yes

### User Modifications

I am currently trying to change the heat in the world generation config to check it that might resolve the issue.

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

epiccat#2540

**Comment by NielsPilgaard** [comment] 2022-10-15 13:04
Duplicate of #1973

**Closed by NielsPilgaard** 2022-10-15 13:04 UTC
Labels: Bug
