### ISSUE TITLE
Replace normal AE2 with AE2 Unofficial Extended Life

### ISSUE THREAD

**Issue by Anthonity** [EnigmaticaModpacks/Enigmatica2Expert#2080] opened 2022-12-15 14:59 UTC
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life

### Why would you like the mod added?

AE2UEL is more performant than normal AE2. The pattern expansion cards would also be really nice addition

**Comment by Kanzaji** [comment] 2022-12-15 15:15
Duplicate of #2045

**Closed** 2022-12-15 17:34 UTC
Labels: Duplicate

**Comment by Anthonity** [comment] 2023-02-21 10:27
bruh
