### ISSUE TITLE
Advanced Rocketry Fuel Loader only accepts Advanced Rocketry Rocket Fuel

### ISSUE THREAD

**Issue by BranDynamite** [EnigmaticaModpacks/Enigmatica2Expert#1948] opened 2021-08-25 01:55 UTC
**Modpack version**
1.83

**Issue**
The Crystallizer Multiblock no longer require 2 coils but instead a fluid input hatch and a fluid output hatch in place of the coils

**Logs**
https://i.imgur.com/DA0mlro.png

**Comment by BranDynamite** [comment] 2021-08-25 02:55
This seems to be a problem with other machines as well except they're replaced by diffrent blocks

**Comment by BranDynamite** [comment] 2021-08-25 03:03
Also the Rolling machine multiblock is just broken, all the block placements are completely messed up

**Comment by NillerMedDild** [comment] 2021-08-25 04:29
Sounds like it just changed? Do they still work? Possible duplicate of #1943

**Comment by BranDynamite** [comment] 2021-08-25 04:54
well maybe it has been changed, but the crystallizer does not have any fluid crafting recipes. Also I don't know if I should make a separate issue for this but the fuel loader isn't accepting any liquids

**Comment by NillerMedDild** [comment] 2021-08-25 05:53
Hmm, sounds like a separate issue, I'll change this one to the Fuel Loader thingie.

**Comment by NillerMedDild** [comment] 2021-08-25 11:12
The Rocket Fluid loader does accept fluids, I can't reproduce the issue.

![billede](https://user-images.githubusercontent.com/21295394/130742696-eeb9bb56-c2d6-42ae-81dc-a3394dc79dd8.png)
![billede](https://user-images.githubusercontent.com/21295394/130742732-cb4237e9-c21b-446d-a406-fd507062b621.png)

**Comment by BranDynamite** [comment] 2021-08-25 14:35
Are you on version 1.83?
Also I do not see any of the side configs in the gui.
Here are some screenshots showing the fuel loader not accepting liquid oxygen or starlight
https://i.imgur.com/E1UaiEd.png
https://i.imgur.com/Bfna9Kj.png

**Comment by NillerMedDild** [comment] 2021-08-25 15:11
Yes I'm on version 1.83
Are you using the Rocket Fuel Loader? The `Fuel Station` label in the screenshots suggest otherwise.

**Comment by BranDynamite** [comment] 2021-08-25 15:35
oh nvm I used the wrong block

**Comment by Nabbieshtron** [comment] 2021-09-25 12:05
I can load blazing pyrotheum no problem but cant fly to luna with a rocket

**Comment by dooms247** [comment] 2021-09-30 20:37
The corrected config leaves out Mekanism Liquid Oxygen, which the questbook mentions you can use.

**Comment by Mg138** [comment] 2021-10-01 06:28
I did ask about Liquid Oxygen, but it remained unanswered

**Comment by NillerMedDild** [comment] 2021-10-01 18:33
Right, I'll get that re-added too :)

**Comment by Terra-B-Welch** [comment] 2022-01-24 08:16
has this been addressed at all? Having just gotten into advanced rocketry I'm wondering, if the server owner adds in the fix mentioned above to the server config, will it work?

**Comment by NillerMedDild** [comment] 2022-01-24 08:49
> has this been addressed at all? Having just gotten into advanced rocketry I'm wondering, if the server owner adds in the fix mentioned above to the server config, will it work?

It will yes.

**Comment by Arithmion** [comment] 2022-02-06 17:07
Question about this: The original mod uses the electrolyser to create hydrogen and oxygen, then you have two options: Create the **bipropellant** engine and use both the liquid hydrogen and the liquid oxygen to fly, or use the chemical reactor to create rocket fuel for the **monopropellant** engine. I saw above that you were planning on adding oxygen in as a viable fuel like the other fuels. Was the intention in this modpack to change the default behavior to an easier behavior, so that only liquid oxygen is needed as a monopropellant? Or was the intention to use liquid oxygen + hydrogen as a bipropellant fuel? The config file lists hydrogen as the only viable bipropellant fuel, so the liquid oxygen may need to be added there rather than the rocket fuels list mentioned by Mg138 (a few lines above it).

If the intention is to have the oxygen be a bipropellant fuel, I recommend changing the QuestBook to clarify that Liquid Oxygen and Hydrogen are viable bipropellant fuels, and either recommending that the player visit the wiki (http://arwiki.dmodoomsirius.me/AdvancedRocketry/1.12.2/blocks/RocketEngine.php) or adding this line into the QuestBook (directly from the wiki): There are two types of engines each with a basic and advanced engine. Monopropellant uses 2 mB/t of rocket fuel. Bipropellant uses 1mB/t each of hydrogen and oxygen and requires 1 of each tank on the rocket.

Please also note that if the intention is to have the player use the bipropellant engine, this requires more titanium, which will likely force the player to use the Advanced Metallurgic Fabricator from Modular Machinery.

Thank you so much, I love your pack!

**Comment by NillerMedDild** [comment] 2022-02-07 18:57
Iirc the bipropellant engine wasn't implemented when we made the quests :P 
Sounds like liquid oxygen shouldn't be a viable monopropellant fuel now, we'll get that sorted 👍... one day, hopefully

**Comment by Arithmion** [comment] 2022-02-07 21:36
Ah, gotcha, thanks for the help! Turns out that the config has a separate fuel list for oxidizers, so my other change is unnecessary. As it stands now, for anybody reading this later, Mg138 above has the fix for adding everything but the oxygen. The liquid oxygen can be used as fuel only for the bipropellant engine, see the advanced rocketry wiki mentioned in my earlier post for details.

**Comment by toastonrye** [comment] 2022-03-05 05:17
> Correct config:
> 
> ```
> S:rocketFuels <
>     rocketfuel;2
>     refined_fuel;2
>     pyrotheum;2
>     neutron;8
>     ic2uu_matter;16
>     astralsorcery.liquidstarlight;3
>  >
> ```

I updated my advancedRocketry.cfg and restarted my server but the fueling station still doesn't take astral starlight? v1.83 of the modpack

**Comment by GrimReaper1982** [comment] 2022-09-11 10:20
Hello there,

i just found this threat before i was reporting the issue with the rocket fuels in 1.83.
Since i found out yesterday that the rockets vom AR only accept the AR rocket fuel,
i was testing things out and looked into my old E2E Versions (1.79a for example).

If you replace the following lines in the AR config for the accepted fuels, all the mentioned
fuels will work again in 1.83:

-------------------------------------------------------------------

   # List of fluid names for fluids that can be used as rocket fuel
    S:rocketFuels <
        rocketfuel
        rocket_fuel
        refined_fuel
        pyrotheum
        neutron
        liquidoxygen
        ic2uu_matter
        astralsorcery.liquidstarlight
     >
-------------------------------------------------------------------

I don`t know if the ";" als delimiter is a problem. This needs to be tested still, but the lines i`ve posted work 100% :)

/cheers

**Closed** 2022-10-16 17:10 UTC
Labels: Bug
